# models an error generated by the sms decoding system
class Sms::DecodingError < Sms::Errors::Error
  attr_reader :type, :params
  def initialize(type, params = {})
    super(type)
    @type = type
    @params = params
  end

  def to_s
    super + " #{@params.inspect}"
  end
end
