# frozen_string_literal: true

# models an error generated by the sms decoding system
module Sms
  class DecodingError < Sms::Errors::Error
    attr_reader :type, :params
    def initialize(type, params = {})
      super(type)
      @type = type
      @params = params
    end

    def to_s
      super + " #{@params.inspect}"
    end
  end
end
