# models an error generated by the sms system
module Sms
  module Errors
    # base error class
    class Error < StandardError
    end

    # error indicating that the entire operation was not able to succeed
    class FatalError < Error
    end

    # some of the operation succeeded but included some errors
    class PartialError < Error
    end
  end
end
