env:
  es6: true
  jest: true
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/all
globals:
  React: true
  ELMO: true
  $: true
  I18n: true
  console: true
rules:
  array-bracket-spacing: error
  arrow-body-style: error
  arrow-spacing: error
  block-spacing: error
  brace-style: error
  camelcase: error
  capitalized-comments: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this:
    - error
    - self
  curly: error
  eqeqeq: error
  func-call-spacing: error
  func-name-matching: error
  func-style: error
  function-paren-newline:
    - error
    - consistent
  implicit-arrow-linebreak: error
  indent:
    - error
    - 2
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  max-len:
    - error
    -
      code: 110
  multiline-comment-style: error
  new-cap: error
  new-parens: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    -
      max: 1
  no-unneeded-ternary: error
  no-unused-vars: 0
  no-var: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    -
      consistent: true
  object-curly-spacing: error
  padded-blocks:
    - error
    - never
  quotes: error
  react/destructuring-assignment: 0
  react/jsx-closing-bracket-location:
    - error
    - after-props
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-max-depth:
    - error
    -
      max: 3
  react/jsx-no-undef: 0
  react/jsx-wrap-multilines: error
  react/no-set-state: 0
  react/react-in-jsx-scope: 0
  react/require-optimization: 0
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-curly-spacing: error
  template-tag-spacing: error
  vars-on-top: error
  yield-star-spacing: error
