source 'http://rubygems.org'

gem 'rails', '3.2.9'
gem 'authlogic'
gem 'rake'
gem 'mysql2'
gem 'will_paginate'
gem 'configatron'
gem 'libxml-ruby'
gem 'fastercsv'
gem 'rdiscount'
gem 'jquery-rails'
gem 'rmagick'
