source 'http://rubygems.org'

gem 'rails', '3.1.6'
gem 'authlogic'
gem 'rake'
gem 'mysql'
gem 'will_paginate'
gem 'configatron'
gem 'libxml-ruby'
gem 'fastercsv'
gem 'yard'
gem 'rdiscount'
gem 'jquery-rails'
gem 'rmagick'