import Enzyme from "enzyme";
import Adapter from "enzyme-adapter-react-16";
import I18n from "i18n-js";

// eslint-disable-next-line no-undef
window.I18n = I18n;

// This file can be generated by `rails i18n:js:export`.
require("../../app/assets/javascripts/i18n/translations");

Enzyme.configure({
  adapter: new Adapter(),
});
