# frozen_string_literal: true

module Themeing
  # Preprocesses application.scss to create combinations for themes and LTR/RTL
  class ScssPreprocessor
    def run
      %w[nemo elmo custom].each do |theme|
        next unless File.exist?(themes_dir.join("_#{theme}_theme.scss"))
        %w[ltr rtl].each do |direction|
          create_file_for(theme, direction)
        end
      end
    end

    private

    def create_file_for(theme, direction)
      filename = "application_#{theme}_#{direction}.scss"
      puts "Writing #{filename}" unless Rails.env.test?
      File.open(File.join(styles_dir, filename), "w") do |f|
        out = original_scss.gsub("@@@theme@@@", "#{theme}_theme").gsub!("@@@direction@@@", direction)
        f.write(out)
      end
    end

    def original_scss
      @original_scss ||= replace_top_comment(File.read(app_scss_file))
    end

    def replace_top_comment(scss)
      lines = scss.split("\n")
      loop { lines[0].match?(%r{\A(//|\w*\z)}) ? lines.shift : break }
      +"// THIS FILE IS AUTO-GENERATED BY rake scss:preprocess. DO NOT EDIT DIRECTLY!\n\n" <<
        lines.join("\n")
    end

    def styles_dir
      @styles_dir ||= Rails.root.join("app", "assets", "stylesheets")
    end

    def app_scss_file
      styles_dir.join("application.scss")
    end

    def themes_dir
      styles_dir.join("all", "themes")
    end
  end
end
