# frozen_string_literal: true

class RemoveOldIdCols < ActiveRecord::Migration[5.2]
  def up # rubocop:disable Metrics/MethodLength, Metrics/AbcSize -- comprehension not an issue
    remove_column :answers, :old_id
    remove_column :answers, :option_old_id
    remove_column :answers, :questioning_old_id
    remove_column :answers, :response_old_id
    remove_column :assignments, :mission_old_id
    remove_column :assignments, :old_id
    remove_column :assignments, :user_old_id
    remove_column :broadcast_addressings, :addressee_old_id
    remove_column :broadcast_addressings, :broadcast_old_id
    remove_column :broadcast_addressings, :old_id
    remove_column :broadcasts, :mission_old_id
    remove_column :broadcasts, :old_id
    remove_column :choices, :answer_old_id
    remove_column :choices, :old_id
    remove_column :choices, :option_old_id
    remove_column :conditions, :mission_old_id
    remove_column :conditions, :old_id
    remove_column :conditions, :option_node_old_id
    remove_column :conditions, :questioning_old_id
    remove_column :conditions, :ref_qing_old_id
    remove_column :form_forwardings, :form_old_id
    remove_column :form_forwardings, :old_id
    remove_column :form_forwardings, :recipient_old_id
    remove_column :form_items, :mission_old_id
    remove_column :form_versions, :form_old_id
    remove_column :form_versions, :old_id
    remove_column :forms, :current_version_old_id
    remove_column :forms, :mission_old_id
    remove_column :forms, :old_id
    remove_column :forms, :original_old_id
    remove_column :forms, :root_old_id
    remove_column :media_objects, :answer_old_id
    remove_column :media_objects, :old_id
    remove_column :missions, :old_id
    remove_column :option_nodes, :mission_old_id
    remove_column :option_nodes, :option_old_id
    remove_column :option_nodes, :option_set_old_id
    remove_column :option_nodes, :original_old_id
    remove_column :option_sets, :mission_old_id
    remove_column :option_sets, :old_id
    remove_column :option_sets, :original_old_id
    remove_column :option_sets, :root_node_old_id
    remove_column :options, :mission_old_id
    remove_column :options, :old_id
    remove_column :questions, :mission_old_id
    remove_column :questions, :old_id
    remove_column :questions, :option_set_old_id
    remove_column :questions, :original_old_id
    remove_column :report_calculations, :old_id
    remove_column :report_calculations, :question1_old_id
    remove_column :report_calculations, :report_report_old_id
    remove_column :report_option_set_choices, :old_id
    remove_column :report_option_set_choices, :option_set_old_id
    remove_column :report_option_set_choices, :report_report_old_id
    remove_column :report_reports, :creator_old_id
    remove_column :report_reports, :disagg_qing_old_id
    remove_column :report_reports, :form_old_id
    remove_column :report_reports, :mission_old_id
    remove_column :report_reports, :old_id
    remove_column :responses, :checked_out_by_old_id
    remove_column :responses, :form_old_id
    remove_column :responses, :mission_old_id
    remove_column :responses, :reviewer_old_id
    remove_column :responses, :user_old_id
    remove_column :settings, :mission_old_id
    remove_column :settings, :old_id
    remove_column :sms_messages, :broadcast_old_id
    remove_column :sms_messages, :mission_old_id
    remove_column :sms_messages, :old_id
    remove_column :sms_messages, :reply_to_old_id
    remove_column :sms_messages, :user_old_id
    remove_column :taggings, :old_id
    remove_column :taggings, :question_old_id
    remove_column :taggings, :tag_old_id
    remove_column :tags, :mission_old_id
    remove_column :tags, :old_id
    remove_column :user_group_assignments, :old_id
    remove_column :user_group_assignments, :user_group_old_id
    remove_column :user_group_assignments, :user_old_id
    remove_column :user_groups, :mission_old_id
    remove_column :user_groups, :old_id
    remove_column :users, :last_mission_old_id
    remove_column :users, :old_id
    remove_column :whitelistings, :old_id
    remove_column :whitelistings, :user_old_id
    remove_column :whitelistings, :whitelistable_old_id
  end
end
